var mainNav = [
    {
        title:"工具",
        nav:[
            {
                navType:"CSS工具",
                nav:[
                    {
                        text:"渐变在线生成",
                        link:"http://www.colorzilla.com/gradient-editor/",
                        icon:"https://www.colorzilla.com/firefox/images/logo-50.png"
                    },
                    {
                        text:"渐变生成（新）",
                        link:"https://www.grabient.com/"
                    },
                    {
                        text:"投影生成",
                        link:"https://www.html.cn/tool/css3Preview/Box-Shadow.html"
                    },
                    {
                        text:"动画贝塞尔",
                        link:"http://xuanfengge.com/easeing/ceaser/"
                    },
                    {
                        text:"背景平铺",
                        link:"https://leaverou.github.io/css3patterns/#"
                    },
                    {
                        text:"形状生成",
                        link:"http://tools.jb51.net/code/css3path"
                    },
                    {
                        text:"动画工具",
                        link:"https://www.w3cways.com/css3-animation-tool"
                    },
                    {
                        text:"文本绕排",
                        link:"http://csswarp.eleqtriq.com/"
                    },
                    {
                        text:"CSS集合",
                        link:"https://qishaoxuan.github.io/css_tricks/createTriangle/"
                    },
                    {
                        text:"动画贝塞尔（新）",
                        link:"https://cubic-bezier.com/#0,.95,0,.97"
                    },
                    {
                        text:"loading",
                        link:"https://loading.io/"
                    }
                ]
            },
            {
                navType:"markDown",
                nav:[
                    {
                        text:"markDown编辑器",
                        link:"https://dillinger.io/"
                    },
                    {
                        text:"markDown在线",
                        link:"https://www.mdeditor.com/"
                    }
                ]
            },
            {
                navType:"图片",
                nav:[
                    {
                        text:"智图",
                        link:"http://zhitu.isux.us/"
                    },
                    {
                        text:"占位图",
                        link:"https://tool.lu/imageholder/"
                    },
                    {
                        text:"tinypng",
                        link:"https://tinypng.com/"
                    }
                ]
            },
            {
                navType:"代码片段",
                nav:[
                    {
                        text:"runJs",
                        link:"https://runjs.cn/"
                    },
                    {
                        text:"代码片段",
                        link:"https://carbon.now.sh/?bg=rgba(171%2C%20184%2C%20195%2C%201)&t=night-owl&wt=none&l=javascript&ds=true&dsyoff=20px&dsblur=68px&wc=true&wa=true&pv=56px&ph=56px&ln=false&fm=Hack&fs=14px&lh=133%25&si=false&es=1x&wm=false&code=var%2520map%2520%253D%2520%257B%250A%2520%2520%252F*%25E5%259C%25B0%25E5%259B%25BE%25E4%25B8%25BB%25E4%25BD%2593*%252F%250A%2520%2520Map%253A%2520undefined%252C%250A%250A%2520%2520%252F*%25E5%2588%259D%25E5%25A7%258B%25E5%258C%2596*%252F%250A%2520%2520init%253A%2520function%2520()%2520%257B%250A%2520%2520%2520%2520this.Map%2520%253D%2520new%2520BMap.Map(%2522mapContener%2522)%253B%250A%2520%2520%2520%2520this.Map.centerAndZoom(new%2520BMap.Point(116.404%252C%252039.915)%252C%252011)%253B%250A%2520%2520%257D%250A%257D%253B"
                    }
                ]
            },
            {
                navType:"请求",
                nav:[
                    {
                        text:"soso API",
                        link:"http://api.i84.com.cn/"
                    },
                    {
                        text:"easyMock",
                        link:"https://www.easy-mock.com/login"
                    }
                ]
            },
            {
                navType:"SVG",
                nav:[
                    {
                        text:"SVG压缩",
                        link:"https://www.zhangxinxu.com/sp/svgo/"
                    }
                ]
            },
            {
                navType:"转换工具",
                nav:[
                    {
                        text:"小程序icon转换",
                        link:"https://transfonter.org/"
                    },
                    {
                        text:"icon转字体",
                        link:"https://icomoon.io/"
                    },
                    {
                        text:"图片转base64",
                        link:"http://tool.chinaz.com/tools/imgtobase"
                    }
                ]
            },
            {
                navType:"字体/图标",
                nav:[
                    {
                        text:"制作ico",
                        link:"http://www.bitbug.net/"
                    },
                    {
                        text:"字体编辑器",
                        link:"https://www.lcddjm.com/font"
                    },
                    {
                        text:"百度字体编辑器",
                        link:"http://fontstore.baidu.com/static/editor/index.html#"
                    },
                    {
                        text:"项目小徽标",
                        link:"https://shields.io/category/build/"
                    },
                    {
                        text:"阿里巴巴矢量图标库",
                        link:"http://www.iconfont.cn/"
                    }
                ]
            },
            {
                navType:"地图辅助",
                nav:[
                    {
                        text:"百度地图生成器",
                        link:"http://api.map.baidu.com/lbsapi/createmap/index.html"
                    }
                ]
            },
            {
                navType:"其他工具",
                nav:[
                    {
                        text:"浏览器版本查看",
                        link:"https://browserl.ist/?q=defaults"
                    },
                    {
                        text:"奶牛快传",
                        link:"https://cowtransfer.com/?source=imaring.com"
                    },
                    {
                        text:"emoji",
                        link:"https://www.webfx.com/tools/emoji-cheat-sheet/"
                    },
                    {
                        text:"短链接生成",
                        link:"https://dwz.cn/"
                    },
                    {
                        text:"百度脑图",
                        link:"http://naotu.baidu.com/"
                    },
                ]
            },
        ]
    }
];