export let asideNav = [
    {
        text:"掘金",
        link:"https://juejin.im/timeline",
        icon:"./icon/juejin.ico"
    },
    {
        text:"码云",
        link:"https://gitee.com/",
        icon:"./icon/gitee.ico"
    },
    {
        text:"知乎",
        link:"https://www.zhihu.com/signin?next=%2F",
        icon:"./icon/zhihu.png"
    },
    {
        text:"蓝湖",
        link:"https://lanhuapp.com",
        icon:"https://lhcdn.lanhuapp.com/web/imgs/lanhuLogo1db1cd87.svg"
    },
    {
        text:"apiPost",
        link:"https://www.apipost.cn/",
        icon:"./icon/apipost.svg"
    },
    {
        text:"草料二维码",
        link:"https://cli.im/",
        icon:"./icon/caoliao.ico"
    },
    {
        text:"tinypng，压缩图片",
        link:"https://tinypng.com/",
        icon:"./icon/tinypng.ico"
    },
    {
        text:"腾讯翻译君",
        link:"https://fanyi.qq.com/",
        icon:"./icon/qq.ico"
    },
    {
        text:"微信公众平台",
        link:"https://mp.weixin.qq.com/",
        icon:"./icon/weixin.ico"
    },
    {
        text: "阿里图标库",
        link: "http://www.iconfont.cn/",
        icon: "./icon/iconfont.ico"
    },
];
